# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "mohri"
application_url = "https://mohri-shopify.pixelatedcode.com"
embedded = true
client_id = "87a152be5a73bfd75eebd168ea4ea292"

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders, read_products, read_customers"

[auth]
redirect_urls = [ "https://mohri-shopify.pixelatedcode.com/api/auth" ]
