# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5ac62fed302c86669a893447bab8e5b8"
application_url = "https://example.com"
embedded = true
name = "pixi-mento"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_metaobjects,write_metaobject_definitions"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[webhooks]
api_version = "2026-07"
